environments:
    development: [localhost]
    staging:     [stage.RocketShip.ca]
    production:  [RocketShip.ca]

# Set the environment for the command line interpreter
cli: development

# Set available permissions for the API
api:
  scopes: []