## Database configurations

database:
    development:
        host: localhost
        port: 27017
        user: ""
        password: ""
        database: RocketShip

    staging:
        host: localhost
        port: 27017
        user: ""
        password: ""
        database: RocketShip

    production:
        host: localhost
        port: 27017
        user: ""
        password: ""
        database: RocketShip
