patterns:
    userid: (:param)         # (:string) = anything, (:any) = anything including '/', (:num) = numeric

ajax:
    uri:
        fr: /ajax/fr/(:string)/
        en: /ajax/en/(:string)/
    action: dispatcher@ajax
    secure: no
    enforce: no
    allow: all

######## START HERE ########

default:
    uri:
        fr: /
        en: /en
    action: index@default    # method@controller
    secure: no               # use https?
    enforce: no              # enforce locale rule
    allow: all               # all or ip or [ip1, ip2, ip3]
